# Generated by Django 4.1.7 on 2023-03-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
